services:
  postgres:
    container_name: hwheels-db
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - hwheels_api_data:/var/lib/postgresql/data

volumes:
  hwheels_api_data:
